apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ajayamundla/argo-poc.git
    targetRevision: main
    path: apps/sample-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
